apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cobank-vs
  namespace: cobank
spec:
  hosts:
  - "cobank.example.com"
  gateways:
  - cobank-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend
        port:
          number: 80
